name: Build, Test, SCA and SAST
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4
       - run: npm install
       - run: npm run build   # Build the app
       - run: npm test       # Execute tests

       - name: Run SCA 
         run: npm audit

       - name: Run Bearer SAST
         uses: bearer/bearer-action@v2
         with:
          exit-code: 1
